In [ ]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objects as go
import plotly.express as px

In [ ]:
match = pd.read_csv('/content/drive/MyDrive/Data_set_local/matches.csv')
delivery = pd.read_csv('/content/drive/MyDrive/Data_set_local/deliveries.csv')

In [ ]:
ipl = delivery.merge(match , left_on='match_id',right_on ='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [ ]:
ipl.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date', 'team1',
       'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied',
       'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue',
       'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [ ]:
# scatter plots
#top 50 batsman
top_50 = ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.tolist()
new_ipl = ipl[ipl['batsman'].isin(top_50)]

In [ ]:
runs  = new_ipl.groupby('batsman')['batsman_runs'].sum()
ball = new_ipl.groupby('batsman')['batsman_runs'].count()

In [ ]:
sr = (runs /ball) *100
sr = sr.reset_index()

In [ ]:
sr = sr.rename(columns={'batsman_runs':'str'})

In [ ]:
runs

batsman
AB de Villiers      3486
AC Gilchrist        2069
AJ Finch            1604
AM Rahane           3057
AT Rayudu           2416
BB McCullum         2755
BJ Hodge            1400
CH Gayle            3651
DA Miller           1563
DA Warner           4014
DJ Bravo            1262
DJ Hussey           1322
DPMD Jayawardene    1808
DR Smith            2385
F du Plessis        1295
G Gambhir           4132
GJ Maxwell          1229
JH Kallis           2427
JP Duminy           1993
KA Pollard          2354
KC Sangakkara       1687
KD Karthik          2903
KK Nair             1158
M Vijay             2511
MEK Hussey          1977
MK Pandey           2223
MK Tiwary           1648
MS Dhoni            3560
NV Ojha             1553
PA Patel            2322
R Dravid            2174
RA Jadeja           1732
RG Sharma           4207
RV Uthappa          3778
S Badrinath         1441
S Dhawan            3561
SC Ganguly          1349
SE Marsh            2489
SK Raina            4548
SPD Smith           1713
SR Tendulkar        2334
SR Watson           2628
SS Tiwary           1276
SV Samson           1426
TM Dilshan          1153
V Kohli             4423
V Sehwag            2728
WP Saha             1557
YK Pathan           2922
Yuvraj Singh        2591
Name: batsman_runs, dtype: int64

In [ ]:
out  =ipl[ipl['player_dismissed'].isin(top_50)]
nout =out['player_dismissed'].value_counts().sort_index()

In [ ]:
avg = runs/nout
avg = avg.reset_index()
avg.rename(columns={0:'avg'} ,inplace =True)
avg = avg.merge(sr,on='batsman')
avg

             batsman        avg         str
0     AB de Villiers  38.307692  145.129059
1       AC Gilchrist  27.223684  133.054662
2           AJ Finch  27.186441  126.299213
3          AM Rahane  33.593407  117.486549
4          AT Rayudu  27.146067  123.014257
5        BB McCullum  28.112245  126.318203
6           BJ Hodge  33.333333  121.422376
7           CH Gayle  41.022472  144.194313
8          DA Miller  34.733333  137.709251
9          DA Warner  40.140000  138.318401
10          DJ Bravo  22.945455  122.286822
11         DJ Hussey  26.979592  120.072661
12  DPMD Jayawardene  28.250000  118.791064
13          DR Smith  28.392857  132.279534
14      F du Plessis  30.116279  124.161074
15         G Gambhir  31.541985  120.361200
16        GJ Maxwell  25.081633  157.564103
17         JH Kallis  28.552941  105.936272
18         JP Duminy  39.860000  121.970624
19        KA Pollard  28.707317  140.621266
20     KC Sangakkara  25.953846  118.469101
21        KD Karthik  24.811966  123.008475
22           KK Nair  25.173913  124.650161
23           M Vijay  26.431579  120.028681
24        MEK Hussey  38.764706  119.963592
25         MK Pandey  28.500000  116.938453
26         MK Tiwary  29.428571  114.127424
27          MS Dhoni  37.872340  132.835821
28           NV Ojha  20.986486  114.528024
29          PA Patel  21.700935  112.718447
30          R Dravid  28.233766  113.347237
31         RA Jadeja  24.055556  118.792867
32         RG Sharma  32.612403  128.497251
33        RV Uthappa  29.515625  127.635135
34       S Badrinath  30.659574  115.742972
35          S Dhawan  32.669725  118.502496
36        SC Ganguly  25.452830  101.734540
37          SE Marsh  39.507937  130.109775
38          SK Raina  33.940299  134.995548
39         SPD Smith  37.239130  128.507127
40      SR Tendulkar  33.826087  114.187867
41         SR Watson  30.917647  134.838379
42         SS Tiwary  28.355556  114.851485
43         SV Samson  25.464286  122.403433
44        TM Dilshan  26.813953  110.124164
45           V Kohli  37.483051  126.588437
46          V Sehwag  27.555556  148.827059
47           WP Saha  25.524590  127.727646
48         YK Pathan  29.816327  140.751445
49      Yuvraj Singh  25.653465  126.390244

In [ ]:
#scatter plot
trace = go.Scatter(x=avg['avg'],y=avg['str'] ,
                   mode='markers' ,
                   text = avg['batsman'],
                   marker = {'color':'#00a65a','size':16})
data =[trace]
layout = go.Layout(title='AVG vs STR',
                   xaxis={'title':'Batsman Average'},
                   yaxis ={'title':'Batsman Str'})
fig = go.Figure(data=data ,layout=layout)
pyo.plot(fig , filename='avg_vs_str.html')

'avg_vs_str.html'

In [ ]:
#scatter plot
trace = go.Scatter(x=avg['avg'],y=avg['str'] ,

                   text = avg['batsman'],
                   marker = {'color':'#00a65a','size':16})
data =[trace]
layout = go.Layout(title='AVG vs STR',
                   xaxis={'title':'Batsman Average'},
                   yaxis ={'title':'Batsman Str'})
fig = go.Figure(data=data ,layout=layout)
pyo.plot(fig, filename = 'line.html')

'line.html'

In [ ]:
ipl.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date', 'team1',
       'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied',
       'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue',
       'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [ ]:
ipl1 =ipl[ipl['batsman'] == 'V Kohli']
performance = ipl.groupby('season')['batsman_runs'].sum()
performance

season
2008    16809
2009    15376
2010    17754
2011    19928
2012    21322
2013    21487
2014    17943
2015    17427
2016    17963
2017    17920
Name: batsman_runs, dtype: int64

In [ ]:
#line chart
trace =go.Scatter(x=performance.index ,y = performance.values ,
                  mode ='lines')
data = [trace]
fig = go.Figure(data=data, layout = layout)
pyo.plot(fig)

'temp-plot.html'

In [ ]:
# ipl1 =ipl[ipl['batsman'] == 'V Kohli']
# performance = ipl.groupby('season')['batsman_runs'].sum()
# performance
ipl2 =ipl[ipl['batsman'] == 'MS Dhoni']
performance1 = ipl1.groupby('season')['batsman_runs'].sum()
performance1

season
2008    414
2009    332
2010    287
2011    392
2012    357
2013    461
2014    371
2015    372
2016    284
2017    290
Name: batsman_runs, dtype: int64

In [ ]:
#line chart
trace1 =go.Scatter(x=performance.index ,y = performance.values ,
                  mode ='lines')

trace2 =go.Scatter(x=performance1.index ,y = performance1.values ,
                  mode ='lines')
layout = go.Layout(title = 'YoY Performance')
data = [trace1 ,trace2]
fig = go.Figure(data=data, layout = layout)
pyo.plot(fig ,filename='com.html')

'com.html'

In [ ]:
#multipe line charts
def batsman_comp(*name):
    data = []
    for i in name:
        single = ipl[ipl['batsman'] == i]
        performance = single.groupby('season')['batsman_runs'].sum().reset_index()

        trace = go.Scatter(x = performance['season'] ,y =performance['batsman_runs']
                          ,mode = 'lines + markers' ,name =i)

        data.append(trace)
    layout = go.Layout(title = 'Batsman Runs Comparison',
                       xaxis = {'title':'Season'},
                       yaxis = {'title':'Runs'})


    fig = go.Figure(data = data ,layout= layout)
    pyo.plot(fig ,filename ='Year_by_year')

In [ ]:
batsman_comp('AB de Villiers' ,'DA Warner' , 'RG Sharma' ,'MS Dhoni')

/usr/local/lib/python3.11/dist-packages/plotly/offline/offline.py:557: UserWarning:

Your filename `Year_by_year` didn't end with .html. Adding .html to the end of your file.